version: 2.0

id: telus-colophon-app

about:
  title: telus-colophon-app
  description: Standarized project metadata to specify the components, constructs and authorship of software

contacts:
  - type: Developer Architect
    name: Mauricio Mercado
    email: mauricio.mercado@telus.com
    github: maumercado
  - type: Developer
    name: Sayde Deng
    email: sayde.deng@telus.com
    github: saydex
  - type: Developer
    name: Pramod Mendonca
    email: pramod.mendonca@telus.com
    github: mendoncp
  - type: Architect
    name: Matthew Cantelon
    email: matthew.cantelon@telus.com
    github: mattcan

references:
  - title: Source Code
    uri: https://github.com/telus/telus-colophon-app
  - title: Homepage
    uri: https://colophon.telus.digital

environments:
  - title: NPM Package
    uri: https://www.npmjs.com/package/@telus/colophon-app
    description: Node module
